version: "3"
services:
  db:
    image: postgres:14.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: warnet
      POSTGRES_USER: warnet
    networks:
      - warnet-api

  client-api:
    build:
      context: .
      dockerfile: Dockerfile_api
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - warnet-api
    command: uvicorn client-api.main:app --host 0.0.0.0 --port 8080 --reload

  server-api:
    build:
      context: .
      dockerfile: Dockerfile_api
    ports:
      - "8090:8090"
    volumes:
      - .:/app
    networks:
      - warnet-api
    command: uvicorn server-api.main:app --host 0.0.0.0 --port 8090 --reload

networks:
  warnet-api:
    driver: bridge
