[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "warnet"
description = "Monitor and analyze the emergent behaviours of bitcoin networks"
readme = "README.md"
requires-python = ">=3.10"
keywords = ["bitcoin", "warnet"]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "black==23.7.0",
    "click==8.1.7",
    "docker==6.1.3",
    "flask==2.3.3",
    "Flask-JSONRPC==2.2.2",
    "jsonschema",
    "jsonrpcserver==5.0.3",
    "jsonrpcclient==4.0.0",
    "kubernetes~=28.1.0",
    "networkx==3.1",
    "numpy==1.26.0",
    "rich==13.5.2",
    "tabulate==0.9.0",
    "PyYAML==6.0.1",
]
dynamic = ["version"]

[project.scripts]
warnet = "warnet.server:run_server"
warcli = "cli.main:cli"
