name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions
      - run: ./test/build_branch_test.py
  scenarios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions
      - run: ./test/scenarios_test.py
  rpc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions
      - run: ./test/rpc_test.py
  rpc-k8s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: medyagh/setup-minikube@master
      - run: |
          just kd
          ./test/rpc_test.py --backend=k8s
          just kdd
  graph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions
      - run: ./test/test_graph.py
  ln:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions
      - run: ./test/ln_test.py
